project_id = "wnqvmhcgxnzxkzpzndfi"

[functions.vapi-webhook]
verify_jwt = false

[functions.validate-session]
verify_jwt = false

[functions.initiate-vapi-call]
verify_jwt = false

[functions.start-vapi-call]
verify_jwt = false

[functions.update-call-id]
verify_jwt = false

[functions.submit-questionnaire]
verify_jwt = false
